export const authThemeStyles = {
  light: {
    colors: {
      brand: '#3b82f6',
      brandAccent: '#60a5fa',
      inputBackground: '#f3f4f6',
      inputText: '#1f2937',
      inputPlaceholder: '#9ca3af',
      inputBorder: '#e5e7eb',
      inputBorderHover: '#3b82f6',
      inputBorderFocus: '#3b82f6',
      messageText: '#1f2937',
      messageBackground: '#f3f4f6',
      anchorTextColor: '#3b82f6',
      dividerBackground: '#e5e7eb',
    },
  },
  dark: {
    colors: {
      brand: '#60a5fa',
      brandAccent: '#3b82f6',
      inputBackground: '#111827',
      inputText: '#f3f4f6',
      inputPlaceholder: '#6b7280',
      inputBorder: '#374151',
      inputBorderHover: '#60a5fa',
      inputBorderFocus: '#60a5fa',
      messageText: '#f3f4f6',
      messageBackground: '#111827',
      anchorTextColor: '#60a5fa',
      dividerBackground: '#374151',
    },
  },
  retro: {
    colors: {
      brand: '#cb4b16',
      brandAccent: '#dc322f',
      inputBackground: '#eee8d5',
      inputText: '#586e75',
      inputPlaceholder: '#839496',
      inputBorder: '#93a1a1',
      inputBorderHover: '#cb4b16',
      inputBorderFocus: '#cb4b16',
      messageText: '#586e75',
      messageBackground: '#eee8d5',
      anchorTextColor: '#cb4b16',
      dividerBackground: '#93a1a1',
    },
  },
  multi: {
    colors: {
      brand: '#FDE2F3',
      brandAccent: '#E5BEEC',
      inputBackground: '#917FB3',
      inputText: '#2A2F4F',
      inputPlaceholder: '#E5BEEC',
      inputBorder: '#E5BEEC',
      inputBorderHover: '#FDE2F3',
      inputBorderFocus: '#FDE2F3',
      messageText: '#2A2F4F',
      messageBackground: '#917FB3',
      anchorTextColor: '#FDE2F3',
      dividerBackground: '#E5BEEC',
    },
  },
};
